name: Update Database

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger this on

jobs:
  update_db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PostgreSQL Client
        uses: s3ponia/setup-pgsql@v1

      - name: Execute SQL Query
        run: |
          psql -h ${{ secrets.AWS_RDS_HOST }} \
               -U ${{ secrets.AWS_RDS_USER }} \
               -d ${{ secrets.AWS_RDS_DATABASE }} \
               -p ${{ secrets.AWS_RDS_PORT }} \
               -a -f update.sql
        env:
          PGPASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
